#!/bin/sh

MINGW=/usr/i686-w64-mingw32/sys-root/mingw
export PATH=$PATH:$MINGW/bin
export CFLAGS="-march=pentium3 -mtune=generic -mpreferred-stack-boundary=5"
export CXXFLAGS="$CFLAGS"

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/modules/Win32Toolchain.cmake -DCMAKE_MODULE_PATH=`pwd`/cmake/modules/ $CMAKE_OPTS

