#!/bin/sh

MINGW=/usr/x86_64-w64-mingw32/sys-root/mingw
export PATH=$PATH:$MINGW/bin
export CXXFLAGS="$CFLAGS"

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/modules/Win64Toolchain.cmake -DCMAKE_MODULE_PATH=`pwd`/cmake/modules/ $CMAKE_OPTS

